name: Build Samples

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Set Path
        run: cd $GITHUB_WORKSPACE
      # Assure that our Nuget packages are present
      - name: Nuget Restore
        run: msbuild -t:restore Samples/SampleWPF/SampleWPF.csproj
      # Build our engine lib to make sure it's present for our samples.
      - name: Build IBEngine Debug|x64
        run: msbuild VisualStudio\IceBox.sln -t:IBEngine -p:Configuration=Debug -p:Platform="x64" -m
      # Build our samples
      - name: Build Sample Win32 Debug|x64
        run: msbuild VisualStudio\IceBox.sln -t:Samples\SampleWin32 -p:Configuration=Debug -p:Platform="x64" -m
      - name: Build Sample Win32 Release|x64
        run: msbuild VisualStudio\IceBox.sln -t:Samples\SampleWin32 -p:Configuration=Release -p:Platform="x64" -m
      - name: Build Sample Memory Debug|x64
        run: msbuild VisualStudio\IceBox.sln -t:Samples\SampleMemory -p:Configuration=Debug -p:Platform="x64" -m
      - name: Build Sample Memory Release|x64
        run: msbuild VisualStudio\IceBox.sln -t:Samples\SampleMemory -p:Configuration=Release -p:Platform="x64" -m
      - name: Build Sample WPF Debug|x64
        run: msbuild VisualStudio\IceBox.sln -t:Samples\SampleWPF -p:Configuration=Debug -p:Platform="x64" -m
      - name: Build Sample WPF Release|x64
        run: msbuild VisualStudio\IceBox.sln -t:Samples\SampleWPF -p:Configuration=Release -p:Platform="x64" -m
